### ISSUE TITLE
not run in java 

### ISSUE THREAD

**Issue by bagherhasani** [revely-inc/co.revely.gradient#2]
hello and thank you for wonderful library but when i add the dependency for java and run it crashed 
here is the error
 FATAL EXCEPTION: main
                  Process: com.pratice.kodak.gradient_2, PID: 7467
                  java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
                      at co.revely.gradient.RevelyGradient.<init>(RevelyGradient.kt)
                      at co.revely.gradient.RevelyGradient$Companion.linear(RevelyGradient.kt:24)
                      at co.revely.gradient.RevelyGradient.linear(RevelyGradient.kt)
                      at com.pratice.kodak.gradient_2.MainActivity.onCreate(MainActivity.java:21)
                      at android.app.Activity.performCreate(Activity.java:6877)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3208)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3351)
                      at android.app.ActivityThread.access$1100(ActivityThread.java:222)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:158)
                      at android.app.ActivityThread.main(ActivityThread.java:7230)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics"

**Comment by dejiapps** [comment]
Same here.

**Comment by demogorgorn** [comment]
the same

**Comment by irufuTT** [comment]
The same
